### ISSUE TITLE
Fails to work on InputStream

### ISSUE THREAD

**Issue by mario** [dengyuhan/MediaMetadataRetrieverCompat#10]
InputStreamSource(source.inputStream()) where my source is         

source: BufferedSource,

fails. I mean the input streamsource creation works, but can't get any frames afterwards.

java.lang.IllegalStateException: Failed to decode frame at 2000 microseconds.

**Comment by mario** [comment]
I tried using both ffmpeg and android factories.

**Comment by xiandanin** [comment]
Let me try your url

**Comment by mario** [comment]
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_stereo_abl.mp4

This is it. With AndroidMediaMetadataRetrieverFactory I even get:
2020-01-01 12:20:09.815 1422-1443/? E/MetadataRetrieverClient: retriever is not initialized

**Comment by xiandanin** [comment]
<img src="https://user-images.githubusercontent.com/17588779/71641183-46c08d80-2cd2-11ea-9cf4-ba49f371b1e2.png" width="200"/><img src="https://user-images.githubusercontent.com/17588779/71641184-4b854180-2cd2-11ea-8633-4c0f8df60c3e.png" width="200"/>
ffmpeg can't seem to parse this video, I use `AndroidMediaMetadataRetrieverFactory` to get frames

```
final MediaMetadataRetrieverCompat mmrc = new MediaMetadataRetrieverCompat();
mmrc.setDataSourceOrThrow(new OkHttpSource(url, null), AndroidMediaMetadataRetrieverFactory.class);
```

`InputStreamSource` not applicable for video


### Data source type
* FileSource
* HTTPSource
* UriSource
* FileDescriptorSource
* OkHttpSource (pictures will use OkHttp)
* InputStreamSource (only supports images)
* AssetSource (only supports images)

**Comment by mario** [comment]
Ah :( 

So I've been using (with success) MediaDataSource and MediaMetadataRetriever on API 23 and up. Unfortunately this is not available earlier :( 

Any ideas how to solve this? I would really appreciate it!

(And thanks for your help so far)

**Comment by xiandanin** [comment]
Did not get your point.
Are you going to use before API 23?

**Comment by mario** [comment]
Yes. I need to extract frame at a given time from API 16 all the way to current API levels.

**Comment by xiandanin** [comment]
That can only use ffmpeg.

You may need to ask the author of [FFmpegMediaMetadataRetriever](https://github.com/wseemann/FFmpegMediaMetadataRetriever).

**Comment by mario** [comment]
Ok, thank you :)
