### ISSUE TITLE
java.lang.RuntimeException: setDataSource failed: status = 0x80000000 

### ISSUE THREAD

**Issue by Tans5** [dengyuhan/MediaMetadataRetrieverCompat#12]
我想要获取500多条音频数据的时长的时候，报了`java.lang.RuntimeException: setDataSource failed: status = 0x80000000`错误，不过Android原生的`MediaMetadataRetriever`也有这个问题，获取少数量的音频Metadata没有问题。

**Comment by xiandanin** [comment]
这个异常跟数量关系不大，一般下面的情况会出现：
__文件有问题；路径不对；文件格式不支持；__

可以看一下到哪一个开始抛这个异常，然后检查这个文件
