### ISSUE TITLE
不兼容最新版NDK

### ISSUE THREAD

**Issue by developerzjy** [dengyuhan/MediaMetadataRetrieverCompat#4]
Androidstudio 添加依赖以后，使用最新版NDK编译不过
NDK版本：17.1
报错
Error:Execution failed for task ':example:transformNativeLibsWithStripDebugSymbolForDebug'.
A problem occurred starting process 'command '/Users/yh/Library/Android/sdk/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/bin/mips64el-linux-android-strip''

ndk目录下darwin-x86_64/   之后的子目录没有bin/mips64el-linux-android-strip
使用NDK 16就可以编译过

**Comment by xiandanin** [comment]
demo能跑起来吗

**Comment by developerzjy** [comment]
demo也是这个情况，ndk16可以跑起来，ndk17的话也是这个错误

**Comment by xiandanin** [comment]
尝试排除掉mips

或者单独引用armeabi-v7a
```
implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi-v7a:1.0.14'
```

**Comment by developerzjy** [comment]
单独引用armv7可以，谢谢

**Comment by xiandanin** [comment]
那你的abiFilters也要指定armeabi-v7a
```
ndk {
            abiFilters 'armeabi-v7a'
}
```

下版会解决这个问题

**Comment by developerzjy** [comment]
好的，谢谢
