### ISSUE TITLE
有没有试过这个问题？最后一帧

### ISSUE THREAD

**Issue by RockyQu** [dengyuhan/MediaMetadataRetrieverCompat#5]
https://github.com/wseemann/FFmpegMediaMetadataRetriever/issues/180

**Comment by RockyQu** [comment]
FFmpegMediaMetadataRetriever 取视频的最后一帧取不到，由其在比较短的视频上，比如只有1，2秒的

**Comment by xiandanin** [comment]
有些视频FFmpegMediaMetadataRetriever取不到帧，但是原生API可以取到，所以MediaMetadataRetrieverCompat遇到这种情况会切换实例去处理

**Comment by xiandanin** [comment]
一般都是取关键帧的，要看视频的关键帧间隔，像问题上一定要那么精确的取某一帧那只能自己解码。

**Comment by RockyQu** [comment]
了解了，谢谢
